### ISSUE TITLE
Prepare to upstream

### ISSUE THREAD

**Issue by mattfarina** [samsung-cnct/jenkins-operator#8]
The following is a list of changes needed so that we can upstream the chart:

* [x] Add a readme to the chart (PR at #10)
* [x] Add a NOTES.txt template (PR at #12)
* [x] Use release versions by number for the images and chart version (no pre-release) (PR at #11)
* [x] Document values files things (PR at #12)
* [x] Add maintainers, keywords, sources, icon, and home to the Chart.yaml (PR at #9)

This is based on a quick first pass and may need to be updated as more things are found.
